"theme-bootstrap":
  "use" : "theme"

"pages" :
  "permalink" : "/:relative_path/:filename"
  "rss":
    "enable": false

"assets":
  "rss":
    "enable": false

"base_path" : ""

"site":
  "use" : "ignore"
